### PR TITLE
Implemented a converter from a CRYSTAL23 output file to the TREX-IO format.

### PR DESCRIPTION
**Pull request by kousuke-nakano**
# Implemented a converter from a CRYSTAL23 output file to the TREX-IO format.

Implemented a converter from a CRYSTAL23 output file [https://www.crystal.unito.it] to the TREX-IO format.

How to use this converter:
 - `python src/trexio_tools/converters/crystal_to_trexio.py -c data/crystal23_mgo_lda.out` 

Supports:
 - Only PBC calculations are supported.
 - All RHF, UHF, and ROHF are supported.
 - Both orthorhombic and non-orthorhombic cells are supported.
 - Users should specify the spin state (i.e., 2S+1). The default is 1.
 - CRYSTAL23 is a commercial software package. One should purchase its license to use it [https://www.crystal.unito.it].

### CODE REVIEW

**Review by scemama — APPROVED** [review]

**Comment by q-posev** [comment]
Thanks @kousuke-nakano for your hard work! 

Please do not merge this MR yet, I need to do some reorganization so that converter is compatible with `convert-from` like others. I will push to this branch when it is ready.

**Comment by kousuke-nakano** [comment]
Dear @q-posev, could I merge this pull request?

**Comment by q-posev** [comment]
Sorry for my lare response @kousuke-nakano ! I did not have time integrate your converter so that it can be used via `convert-from`. It is a relatively simple change (just need to call you `crystal_to_trexio` in `convert_from` and add a CLI option for `crystal` code like I did back in the days for your PySCF converter in #15 . 

I guess the goal is to use your converter via `convert-from`, right? Maybe I can have a look this weekend, should be too much work to add it.

**Comment by q-posev** [comment]
OK, @kousuke-nakano  turns out I cannot push to this PR because it's from your fork.
I will merge this PR and prepare another one to integrate your converter into `convert-from`. 
Thanks again, Kousuke!

**Review by q-posev — COMMENTED** [review]
Approved

**Comment by kousuke-nakano** [comment]
Thanks! @q-posev

**Pull request merged**
