### PR TITLE
Previous fix was wrong. Re-fixed

### PR DESCRIPTION
**Pull request by scemama**
The normalization was not applied at the proper place in the previous commit. I fixed it.

### CODE REVIEW

**Comment by q-posev** [comment]
@scemama would it be possible add a regression/unit test for this functionality? I feel like it's something that is easy to break and hard to catch.

**Comment by scemama** [comment]
I just added a test.
Yes, it occured after the sphe->cart conversion. The check-mos was correct in spherical, but wrong after conversion. This explains problems when converting some PySCF spherical files and importing them into QP.

**Comment by scemama** [comment]
I am afraid that adding the qmckl dependency and compiling it will take as much time as the check-mos.... maybe we can just reduce the number of integration grid points. Even with 30 points, i think we can detect if someting is wrong

**Comment by q-posev** [comment]
Yes i also thought that the compilation will be slow. If only someone would make a Python package for qmckl... 😀 

I actually increased the number of points in this MR and fixed the error thresholds for each file. This is the first attempt to address issue #12 but ideally it would be nice to store some converted trexio files as a ref somewhere and do a more rigorous check of converters using these ref files.

**Pull request merged**
